### ISSUE TITLE
Broken Overclocking options 

### ISSUE THREAD

**Issue by TesterNes** [libretro/beetle-pce-libretro#29]
Starting a game with any value in overclock or frame limit section take no effects unless you enter in the option menu -while game is running- and activate/deactivate any feature or change a value.

**Comment by negativeExponent** [comment]
not sure why, but this line is not called on the first iteration of check_variables:
https://github.com/libretro/beetle-pce-libretro/blob/master/libretro.cpp#L1346

i don't know the reason, someone else might know if this causes problems:
@Tatsuya79 - i think you had a hand in the initial porting of this core. you might know something about this

**Comment by Tatsuya79** [comment]
Indeed it's not set at start, I didn't notice as I usually change it at run time.
I've been testing the core when it was made but it wasn't me who wrote most of the code.
It's probably just an oversight.
