### ISSUE TITLE
screen completely distorded on shield tv android

### ISSUE THREAD

**Issue by srk15372** [libretro/beetle-pce-libretro#3]
Hi, I have just update the core on android shield tv and the screen is completely distorded.
like this:

![57054234-880c2380-6c93-11e9-9c06-59022dc76143](https://user-images.githubusercontent.com/40340145/72830519-2fe1db00-3c81-11ea-8384-70c654c705cc.jpg)

I encounter this behaviour on snes9x 6 month ago and it was succefully patched.
hope you could restore this core on android thanks

**Comment by fmaida** [comment]
I can confirm the same behavior on my Amazon Fire Stick 4K. Beetle PCE fast works well instead.
Unfortunately I have no idea about how to extract a log file from my fire stick..

**Comment by mrjschulte** [comment]
Do you have the Pr that fixed the issue affecting this core on android?

**Comment by srk15372** [comment]
hi,
I have just the link below

https://github.com/libretro/snes9x/issues/212

**Comment by tooncoon** [comment]
Retroarch wants textures aligned to 4 bytes. Fix should be here
https://github.com/libretro/beetle-pce-libretro/pull/10

**Comment by srk15372** [comment]
Hi, I have just download the latest core revision on my shield tv android but unfortunaly, the problem remain

**Comment by trioan** [comment]
Based on the snes9x fix,
https://github.com/snes9xgit/snes9x/commit/52f521160a3fed88dcbf8050e41b3c4078fb04d4


I'm guessing that maybe the pitch needs fixing.
https://github.com/libretro/beetle-pce-libretro/pull/12

**Comment by trioan** [comment]
Check tooncoon's comment, it has important information about how the Stella core was fixed.

**Comment by hizzlekizzle** [comment]
Looks like Zelda in the picture? o_O

**Comment by srk15372** [comment]
yes, I post a wrong picture (take these when I have the same problem on snes9x) but this is exactly the same behaviour on this pce core. sorry

**Comment by negativeExponent** [comment]
can you post actual screenshot of this pitch issue? and what game? and what core options are used. might even help to add the retroarch.cfg used.

**Comment by vanfanel** [comment]
This is also happening on Raspberry Pi 4 in Aarch64 mode, using latest GIT version.
Exact same distortion.
Default config options on both RetroArch and the core.
The pce-fast variant looks perfectly well, it only happens on the non-fast core.

**Comment by negativeExponent** [comment]
> This is also happening on Raspberry Pi 4 in Aarch64 mode, using latest GIT version.
> Exact same distortion.
> Default config options on both RetroArch and the core.
> The pce-fast variant looks perfectly well, it only happens on the non-fast core.

are you able to look into it? i would, but i dont have pie4 or any of the said device with the pitch issue. i think the latest fix for this only changed RA's max framebuffer, but the cores fb still has alignment issues

**Comment by twinaphex** [comment]
@vanfanel Is this still an ongoing issue?

**Comment by vanfanel** [comment]
@twinaphex Yes it is :(

**Comment by Tatsuya79** [comment]
This bug is caused by having "show horizontal overscan" set to "auto".
"On" or "off" is fine.

So the issue is certainly there: https://github.com/libretro/beetle-pce-libretro/blob/master/mednafen/pce/vce.cpp#L1134
I guess it's an odd value for the width size causing it on android, while desktop nvidia drivers don't care.

**Comment by Tatsuya79** [comment]
Well, it happened on PC Genjin 2 so it's not just that option...

**Comment by srk15372** [comment]
hi thanks for the tip
unfortunely it dosen't work for me. I test the on and off without sucess.
what a pity we couln't use this core for years.

**Comment by TideGear** [comment]
I can confirm this issue still exists with the latest Beetle PCE core on my Galaxy s20 Ultra. PCE FAST works fine.

**Comment by Tatsuya79** [comment]
Bug with gl (gles), fine with vulkan on my phone.

**Comment by srk15372** [comment]
hi, thanks again it works
I'm dumb I don't think to change the video friver to test
thanks a lot
regards

**Comment by Sanaki** [comment]
Whether or not you've accepted a workaround, the issue isn't fixed, and thus shouldn't be closed. It's still a valid problem for users stuck using gl.
