### ISSUE TITLE
Mednafen  1.29 please many fixes

### ISSUE THREAD

**Issue by Shinobi-1987** [libretro/beetle-pce-libretro#42]
Please update this to 1.29 upstream. Many fixes for pce.

**Comment by LibretroAdmin** [comment]
And as usual, 'many fixes' translates to one obscure glitch being fixed in exactly one game -

https://github.com/libretro/beetle-pce-libretro/pull/43

Here you go regardless.

**Comment by Shinobi-1987** [comment]
thank you!

um no the rtype fix also.



also from 9.xx to 1.xx alot changed and fixed. 


changes here 
[changes.txt](https://github.com/libretro/beetle-pce-libretro/files/8880307/changes.txt)

**Comment by LibretroAdmin** [comment]
Then submit your placebo 'fixes' if they all mattered so much. What has been transferred over is all that there is.

**Comment by Shinobi-1987** [comment]
> Your link doesn't work.
> 
> If you think anything is missing, be sure to submit a PR that actually works and that shows proof of your claims. We don't take advice or lectures from people that don't know how to code and only talk about stuff in readmes or changelogs.

Placebo? I guess the author of the emulator you are using lied? You are a tool.

**Comment by Shinobi-1987** [comment]
January 12, 2022:
	PCE, PCE-Fast: Initialize VCE color table memory at power-on to roughly(without probabilistic bit randomness) match test results from a
	PC Engine Duo instead of just zeroing it; fixes unreadable letters in the password entry screen of "Order of the Griffon".

January 11, 2022:
	PCE: Added patch in the "notes" subdir for extending the upper range of the "pce.slend" setting to 241(not applied in Mednafen due to increasing
	the probability of an extra 8ms of input lag with some games).

December 24, 2021:
	PCE: Fixed incomplete initialization of the VDC BG tile cache; fixes glitches after the boss explodes in "R-Type" under certain
	conditions(more likely to occur in forks of Mednafen).

ecember 31, 2020:
	
	PCE-Fast: Renamed encapsulating namespace from "PCE_Fast" to "MDFN_IEN_PCE_FAST", to match the convention of all other emulation modules.

	Made Emulated* MDFNGI objects constant, copied over to a dynamically-allocated MDFNGI assigned to MDFNGameInfo on game load.

ecember 30, 2020:

	PCE-Fast: Fixed massive overallocation of memory for the VDC background tile cache.


August 24, 2019:
	PCE: Changed the Super CD-ROM^2 memory identification signature to match a Duo instead of a PCE with a system card, to fix compatibility
	issues with some US Super CD-ROM^2 games when using a US system card image, per tip from elmer.

March 18, 2019:
	PCE: Fixed an old bug(looks like from around a decade ago) in the HES playback code; it caused periodic high IRQ latency,
	which resulted in timer IRQ-driven DDA playback sounding rougher than it should have.

November 30, 2018:
	PCE: Increased CD read startup delay per tip from dshadoff.  Fixes ADPCM voice playback	issues in "Downtown Nekketsu Monogatari" when text
	speed is set to fast.

January 12, 2018:
	
	PCE_FAST: Fixed fubared mouse emulation.

April 18, 2017:
	VB, PCE, WonderSwan, MD, GBA: Use fastcall calling convention(on 32-bit x86) in a few (more) places where it makes sense.

**Comment by LibretroAdmin** [comment]
A lot of those things mentioned were inconsequential or did not matter at all.
