### ISSUE TITLE
Aero Blasters crashed

### ISSUE THREAD

**Issue by AngelofMe** [libretro/beetle-pce-libretro#52]
open content
Aero Blasters (Japan)
Aero Blasters (USA)
crashed

**Comment by vanfanel** [comment]
I can confirm that game causes the core to segfault.
It can be avoided by setting the “Show horizontal overscan” core option to OFF.

Happens in arm, aarch64 and x86_64, on GNU/Linux.

It doesn't happen in the pce_fast core.

**Comment by Tatsuya79** [comment]
Doesn't happen on win10 x64.

**Comment by vailkyte** [comment]
Okay on win7 x86 and winxp x86.

Don't know if #69 affects this game.

**Comment by vailkyte** [comment]
@vanfanel 
Can you compile the core in debug mode and test the crash? Maybe it's the optimizer doing bad things.

**Comment by vanfanel** [comment]
I found out that changing the `Last Scanline` core option,  the segfault doesn't appear.

I hope it helps debugging this long-standing issue!

**Comment by rtomasa** [comment]
Definetively the problem is when setting `pce_h_overscan = auto`. This option tries to make auto croping based on some formulas in `vce.cpp` in the next condition: `if(MDFN_GetSettingB("pce.crop_h_overscan"))` resulting in incorrect width (16) and height (30) which is reported as the game geometry, leading to a crash due to libretro frontend not able to manage such bad resolutions.

**Comment by stonegrimm** [comment]
Confirmed in other content too, not only Aero Blasters. Sometimes RA just crashes, sometimes audio works but no viewport shows. Both PCE FAST and Supergrafx work fine however.

**Comment by negativeExponent** [comment]
if anyone is able to compile this on those system and it still crashes, do this and see if it will still crash.

change this line from:
`static int scanline_start, scanline_end;`
to
`static int scanline_start, scanline_end=242;`

https://github.com/libretro/beetle-pce-libretro/blob/957d900d5046182a3d788ca3a3a7d738049e6268/mednafen/pce/vce.cpp#L39

**Comment by vanfanel** [comment]
> if anyone is able to compile this on those system and it still crashes, do this and see if it will still crash.
> 
> change this line from: `static int scanline_start, scanline_end;` to `static int scanline_start, scanline_end=242;`
> 
> https://github.com/libretro/beetle-pce-libretro/blob/957d900d5046182a3d788ca3a3a7d738049e6268/mednafen/pce/vce.cpp#L39

Seems to avoid the crash, indeed!
Tested on X86_64 GNU/Linux, latest stable MESA, Intel XE Graphics, with both GLCORE and Vulkan Retroarch video backends.

**Comment by negativeExponent** [comment]
Good to know. If your able to, please send a PR. Tnx

**Comment by vanfanel** [comment]
Done!
