### ISSUE TITLE
Add force sgx mode for games like darius

### ISSUE THREAD

**Issue by 007mesen** [libretro/beetle-pce-libretro#71]
Add force sgx mode for games like darius

**Comment by bslenul** [comment]
All the games listed here force SGX mode: https://github.com/libretro/beetle-pce-libretro/blob/7f0375608181c02b504d585c788a568522a0606c/mednafen/pce/pce.cpp#L255-L268

so Darius Plus already runs in SGX mode with this core.

Very obvious on the 1st boss, look at all that sprite flickering if I manually remove the game from that list:

https://github.com/libretro/beetle-pce-libretro/assets/33353403/24364efd-6eb5-4fc9-86e4-baaec1a66cd7

vs. how it looks like in SGX mode:

https://github.com/libretro/beetle-pce-libretro/assets/33353403/5953312d-b21b-46b7-9789-68ed768e9aa8

I added Darius Alpha in the list but couldn't see any difference, after some google searches it looks like it's not actually enhanced despite the logo on the box: https://forums.atariage.com/topic/237235-the-official-turbografx-16-thread/page/76/

**Comment by 007mesen** [comment]
Ok. Is there any reason to keep the force sgx core option hidden? It used to be there then some one removed it. What advantage is there to having removed the option to force sgx?

**Comment by bslenul** [comment]
AFAICT it was never an option in the Beetle PCE core, however there is a "Force SuperGrafx Emulation" core option in the Beetle SuperGrafx core.
