### ISSUE TITLE
Update core to 1.29.0

### ISSUE THREAD

**Issue by ToniBC** [libretro/beetle-pce-libretro#9]
Mednafen was recently updated with several corrections of this emulator and it would be nice to include them to improve those small errors. I don't know if some have already been applied, but since the core only reflects that it is in 0.9.48 (PCE), they supposedly were not added.

After 0.9.48 this is what they changed:

PCE: Allocate HuC6280 objects statically instead of dynamically, and removed a layer of indirection for the event handler pointer.
PCE: Moved HuC6280 CPU emulator back into the "pce" directory, since no other emulated systems use it and there are no plans for emulating any such systems(and if there were, new, cleaner HuC6280 emulation code should probably be written).
PCE, PC-FX: Added AVX support to the resampler.
PCE, PC-FX: Made resampler's coefficient memory layout more optimal.
PCE, PC-FX: Added ARM NEON support to the resampler(though it's only compiled in when the compiler is setup to use NEON, such as by passing -mfpu=neon).
PCE, PSX, PCE_FAST: Avoid UB by biasing uintptr_t values instead of pointers directly in the CPU core.
PCE, PCE_FAST: Added support for auto-enabling SuperGrafx emulation with CDs when a mode 1 data track has the 16-byte magic "4D 65 64 6E 61 66 65 6E 74 AB 90 19 42 62 7D E6" at offset 0x86A(assuming 2048 bytes per sector), for homebrew and translations.
PCE: Improved SuperGrafx window handling in 10MHz dot clock modes.
PCE, PCE_FAST: Added a missing sound emulation variable to save states.
PCE: Increased CD read startup delay per tip from dshadoff. Fixes ADPCM voice playback issues in "Downtown Nekketsu Monogatari" when text speed is set to fast.
PCE: Fixed an old bug(looks like from around a decade ago) in the HES playback code; it caused periodic high IRQ latency, which resulted in timer IRQ-driven DDA playback sounding rougher than it should have.
PCE: Changed the Super CD-ROM^2 memory identification signature to match a Duo instead of a PCE with a system card, to fix compatibility issues with some US Super CD-ROM^2 games when using a US system card image, per tip from elmer.

As always, thank you very much for the effort and this is only to remember that it is pending to update the core.

Some things do not belong directly to this core or are shared, but this is how they indicate it. Some of these things may not affect the core, but since I don't know, I am reporting it.

Thank you.

**Comment by Eggo-dotcom** [comment]
to 1.28 at this point.

Is this abandoned?

**Comment by Eggo-dotcom** [comment]
1.29 stable is out, compatibility fixes to commercial titles included.


from 9.40 to now many fixes to pce......

**Comment by Eggo-dotcom** [comment]
Supergrafx core got 1.29!!!

**Comment by Eggo-dotcom** [comment]
Is this going to update ond day or was it a one time port?

**Comment by Eggo-dotcom** [comment]
I have tested and confirmed the updates are needed. not just the version number.

Attached is a list of things this core needs fixed (ie update to 1.29
[changes.txt](https://github.com/libretro/beetle-pce-libretro/files/7987023/changes.txt)
)

**Comment by efrainm23** [comment]
The Saturn core finally got updated to 1.29.0, although cheats are still not working on it. The Supergrafx core has also been updated back in February as mentioned here earlier, but unfortunately its based on the less accurate PCE-Fast. I hope someday this accurate core will get updated.  I know as of a couple of years ago, the accurate core for Retroarch did not even exists, so it has always lagged behind in attention compared to the other PC Engine cores.

**Comment by Shinobi-1987** [comment]
I went back to using the real emulators as a backend and a front end to bring them together. Not as nice as retroarch but i now have all cores up to date.  

Only real need for retroarch on pc is for the front end and extras. 


but if you want up to date cores without extra bugs even using something easy like romshelf does the trick.

**Comment by LibretroAdmin** [comment]
There was exactly one meaningful improvement inbetween all these versions and it affected only one game -

https://github.com/libretro/beetle-pce-libretro/pull/43

Here you go regardless.

It's really disappointing how much users gaslight themselves into thinking massive changes happen in these versions when we have to keep telling them - 80% of these changes are all useless for the libretro core anyway since we hardfork the repo. We don't want all these newer C++ language constructs, we don't want to pull in the bloat, we want to keep any additional enhancements limited ONLY to the core emulation, and not to the frontend-facing parts that we try as much possible to remove or avoid in the libretro core anyway.

**Comment by ToniBC** [comment]
Obviously not all the changes are improvements for the games, as you comment, many are from the system they use, but this would not happen if something as simple as changing the version number, indicating that it is up to date, would give the impression that the cores are up to date.

Anyway, thanks for the info.
